name: wikipedia-lm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - transformers>=4.30.0
  - datasets>=2.12.0
  - tokenizers>=0.13.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - nltk>=3.8
  - matplotlib>=3.7.0
  - jupyter
  - pip
  - pip:
    - wandb